# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ColumnName(object):

    """Implementation of the 'ColumnName' model.

    TODO: type model description here.

    Attributes:
        name (string): The filter name. Will be translated by babel
        operator (string): The filter operation key to use on list filters

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": 'name',
        "operator": 'operator'
    }

    def __init__(self,
                 name=None,
                 operator=None):
        """Constructor for the ColumnName class"""

        # Initialize members of the class
        self.name = name
        self.operator = operator

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get('name')
        operator = dictionary.get('operator')

        # Return an object of this model
        return cls(name,
                   operator)
