# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from manager.models.add_columns import AddColumns
from manager.models.edit_columns import EditColumns


class GetInfoSchema(object):

    """Implementation of the 'get_info_schema' model.

    TODO: type model description here.

    Attributes:
        add_columns (dict): TODO: type description here.
        edit_columns (dict): TODO: type description here.
        keys (list of KeyEnum): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "add_columns": 'add_columns',
        "edit_columns": 'edit_columns',
        "keys": 'keys'
    }

    def __init__(self,
                 add_columns=None,
                 edit_columns=None,
                 keys=None):
        """Constructor for the GetInfoSchema class"""

        # Initialize members of the class
        self.add_columns = add_columns
        self.edit_columns = edit_columns
        self.keys = keys

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        add_columns = AddColumns.from_dictionary(dictionary.get('add_columns')) if dictionary.get('add_columns') else None
        edit_columns = EditColumns.from_dictionary(dictionary.get('edit_columns')) if dictionary.get('edit_columns') else None
        keys = dictionary.get('keys')

        # Return an object of this model
        return cls(add_columns,
                   edit_columns,
                   keys)
