# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Key2Enum(object):

    """Implementation of the 'Key2' enum.

    TODO: type enum description here.

    Attributes:
        LIST_COLUMNS: TODO: type description here.
        ORDER_COLUMNS: TODO: type description here.
        LABEL_COLUMNS: TODO: type description here.
        DESCRIPTION_COLUMNS: TODO: type description here.
        LIST_TITLE: TODO: type description here.
        NONE: TODO: type description here.

    """

    LIST_COLUMNS = 'list_columns'

    ORDER_COLUMNS = 'order_columns'

    LABEL_COLUMNS = 'label_columns'

    DESCRIPTION_COLUMNS = 'description_columns'

    LIST_TITLE = 'list_title'

    NONE = 'none'
