# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from manager.api_helper import APIHelper


class OrderNotesApiPost(object):

    """Implementation of the 'OrderNotesApi.post' model.

    TODO: type model description here.

    Attributes:
        order (object): TODO: type description here.
        changed_by (object): TODO: type description here.
        changed_on (datetime): TODO: type description here.
        created_by (object): TODO: type description here.
        created_on (datetime): TODO: type description here.
        note (string): TODO: type description here.
        mtype (object): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "note": 'note',
        "order": 'Order',
        "changed_by": 'changed_by',
        "changed_on": 'changed_on',
        "created_by": 'created_by',
        "created_on": 'created_on',
        "mtype": 'type'
    }

    def __init__(self,
                 note=None,
                 order=None,
                 changed_by=None,
                 changed_on=None,
                 created_by=None,
                 created_on=None,
                 mtype=None):
        """Constructor for the OrderNotesApiPost class"""

        # Initialize members of the class
        self.order = order
        self.changed_by = changed_by
        self.changed_on = APIHelper.RFC3339DateTime(changed_on) if changed_on else None
        self.created_by = created_by
        self.created_on = APIHelper.RFC3339DateTime(created_on) if created_on else None
        self.note = note
        self.mtype = mtype

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        note = dictionary.get('note')
        order = dictionary.get('Order')
        changed_by = dictionary.get('changed_by')
        changed_on = APIHelper.RFC3339DateTime.from_value(dictionary.get("changed_on")).datetime if dictionary.get("changed_on") else None
        created_by = dictionary.get('created_by')
        created_on = APIHelper.RFC3339DateTime.from_value(dictionary.get("created_on")).datetime if dictionary.get("created_on") else None
        mtype = dictionary.get('type')

        # Return an object of this model
        return cls(note,
                   order,
                   changed_by,
                   changed_on,
                   created_by,
                   created_on,
                   mtype)
