# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderDirectionEnum(object):

    """Implementation of the 'OrderDirection' enum.

    TODO: type enum description here.

    Attributes:
        ASC: TODO: type description here.
        DESC: TODO: type description here.

    """

    ASC = 'asc'

    DESC = 'desc'
