# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from manager.api_helper import APIHelper
from manager.models.order_notes_api_get_order import OrderNotesApiGetOrder
from manager.models.order_notes_api_get_user import OrderNotesApiGetUser


class OrderNotesApiGet(object):

    """Implementation of the 'OrderNotesApi.get' model.

    TODO: type model description here.

    Attributes:
        order (OrderNotesApiGetOrder): TODO: type description here.
        changed_by (OrderNotesApiGetUser): TODO: type description here.
        changed_on (datetime): TODO: type description here.
        created_by (OrderNotesApiGetUser): TODO: type description here.
        created_on (datetime): TODO: type description here.
        note (string): TODO: type description here.
        mtype (object): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "order": 'Order',
        "changed_by": 'changed_by',
        "created_by": 'created_by',
        "note": 'note',
        "changed_on": 'changed_on',
        "created_on": 'created_on',
        "mtype": 'type'
    }

    def __init__(self,
                 order=None,
                 changed_by=None,
                 created_by=None,
                 note=None,
                 changed_on=None,
                 created_on=None,
                 mtype=None):
        """Constructor for the OrderNotesApiGet class"""

        # Initialize members of the class
        self.order = order
        self.changed_by = changed_by
        self.changed_on = APIHelper.RFC3339DateTime(changed_on) if changed_on else None
        self.created_by = created_by
        self.created_on = APIHelper.RFC3339DateTime(created_on) if created_on else None
        self.note = note
        self.mtype = mtype

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        order = OrderNotesApiGetOrder.from_dictionary(dictionary.get('Order')) if dictionary.get('Order') else None
        changed_by = OrderNotesApiGetUser.from_dictionary(dictionary.get('changed_by')) if dictionary.get('changed_by') else None
        created_by = OrderNotesApiGetUser.from_dictionary(dictionary.get('created_by')) if dictionary.get('created_by') else None
        note = dictionary.get('note')
        changed_on = APIHelper.RFC3339DateTime.from_value(dictionary.get("changed_on")).datetime if dictionary.get("changed_on") else None
        created_on = APIHelper.RFC3339DateTime.from_value(dictionary.get("created_on")).datetime if dictionary.get("created_on") else None
        mtype = dictionary.get('type')

        # Return an object of this model
        return cls(order,
                   changed_by,
                   created_by,
                   note,
                   changed_on,
                   created_on,
                   mtype)
