# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ProductNotesApiGetList(object):

    """Implementation of the 'ProductNotesApi.get_list' model.

    TODO: type model description here.

    Attributes:
        action_type (string): TODO: type description here.
        id (int): TODO: type description here.
        note (string): TODO: type description here.
        products_id (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "note": 'note',
        "products_id": 'products_id',
        "action_type": 'action_type',
        "id": 'id'
    }

    def __init__(self,
                 note=None,
                 products_id=None,
                 action_type=None,
                 id=None):
        """Constructor for the ProductNotesApiGetList class"""

        # Initialize members of the class
        self.action_type = action_type
        self.id = id
        self.note = note
        self.products_id = products_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        note = dictionary.get('note')
        products_id = dictionary.get('products_id')
        action_type = dictionary.get('action_type')
        id = dictionary.get('id')

        # Return an object of this model
        return cls(note,
                   products_id,
                   action_type,
                   id)
