# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from manager.api_helper import APIHelper


class ProductsApiGetOrderProducts(object):

    """Implementation of the 'ProductsApi.get.OrderProducts' model.

    TODO: type model description here.

    Attributes:
        changed_on (datetime): TODO: type description here.
        created_on (datetime): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "changed_on": 'changed_on',
        "created_on": 'created_on'
    }

    def __init__(self,
                 changed_on=None,
                 created_on=None):
        """Constructor for the ProductsApiGetOrderProducts class"""

        # Initialize members of the class
        self.changed_on = APIHelper.RFC3339DateTime(changed_on) if changed_on else None
        self.created_on = APIHelper.RFC3339DateTime(created_on) if created_on else None

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        changed_on = APIHelper.RFC3339DateTime.from_value(dictionary.get("changed_on")).datetime if dictionary.get("changed_on") else None
        created_on = APIHelper.RFC3339DateTime.from_value(dictionary.get("created_on")).datetime if dictionary.get("created_on") else None

        # Return an object of this model
        return cls(changed_on,
                   created_on)
