# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SecurityLoginResponse(object):

    """Implementation of the 'Security Login Response' model.

    TODO: type model description here.

    Attributes:
        access_token (string): TODO: type description here.
        refresh_token (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "access_token": 'access_token',
        "refresh_token": 'refresh_token'
    }

    def __init__(self,
                 access_token=None,
                 refresh_token=None):
        """Constructor for the SecurityLoginResponse class"""

        # Initialize members of the class
        self.access_token = access_token
        self.refresh_token = refresh_token

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        access_token = dictionary.get('access_token')
        refresh_token = dictionary.get('refresh_token')

        # Return an object of this model
        return cls(access_token,
                   refresh_token)
