# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusEnum(object):

    """Implementation of the 'Status' enum.

    TODO: type enum description here.

    Attributes:
        OPEN: TODO: type description here.
        PENDING: TODO: type description here.
        ENUM_ACCEPT PAYMENT: TODO: type description here.
        PAID: TODO: type description here.
        ENUM_ORDERED FROM VENDOR: TODO: type description here.
        ENUM_IN TRANSIT: TODO: type description here.
        DELIVERED: TODO: type description here.
        CLOSED: TODO: type description here.

    """

    OPEN = 'open'

    PENDING = 'pending'

    ENUM_ACCEPT_PAYMENT = 'accept payment'

    PAID = 'paid'

    ENUM_ORDERED_FROM_VENDOR = 'ordered from vendor'

    ENUM_IN_TRANSIT = 'in transit'

    DELIVERED = 'delivered'

    CLOSED = 'closed'
