# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from manager.models.vendor_shipping_api_get_list_vendor import VendorShippingApiGetListVendor


class VendorShippingApiGetList(object):

    """Implementation of the 'VendorShippingApi.get_list' model.

    TODO: type model description here.

    Attributes:
        id (int): TODO: type description here.
        name (string): TODO: type description here.
        vendor (VendorShippingApiGetListVendor): TODO: type description here.
        vendor_id (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": 'name',
        "id": 'id',
        "vendor": 'vendor',
        "vendor_id": 'vendor_id'
    }

    def __init__(self,
                 name=None,
                 id=None,
                 vendor=None,
                 vendor_id=None):
        """Constructor for the VendorShippingApiGetList class"""

        # Initialize members of the class
        self.id = id
        self.name = name
        self.vendor = vendor
        self.vendor_id = vendor_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get('name')
        id = dictionary.get('id')
        vendor = VendorShippingApiGetListVendor.from_dictionary(dictionary.get('vendor')) if dictionary.get('vendor') else None
        vendor_id = dictionary.get('vendor_id')

        # Return an object of this model
        return cls(name,
                   id,
                   vendor,
                   vendor_id)
