# -*- coding: utf-8 -*-

"""
manager

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from manager.decorators import lazy_property
from manager.configuration import Configuration
from manager.configuration import Environment
from manager.controllers.customer_api_controller import CustomerApiController
from manager.controllers.menu_controller import MenuController
from manager.controllers.open_api_controller import OpenApiController
from manager.controllers.order_api_controller import OrderApiController
from manager.controllers.order_notes_api_controller\
    import OrderNotesApiController
from manager.controllers.product_notes_api_controller\
    import ProductNotesApiController
from manager.controllers.products_api_controller import ProductsApiController
from manager.controllers.security_controller import SecurityController
from manager.controllers.vendor_api_controller import VendorApiController
from manager.controllers.vendor_contact_api_controller\
    import VendorContactApiController
from manager.controllers.vendor_product_options_api_controller\
    import VendorProductOptionsApiController
from manager.controllers.vendor_shipping_api_controller\
    import VendorShippingApiController
from manager.controllers.websites_api_controller import WebsitesApiController


class ManagerClient(object):

    @lazy_property
    def customer_api(self):
        return CustomerApiController(self.config)

    @lazy_property
    def menu(self):
        return MenuController(self.config)

    @lazy_property
    def open_api(self):
        return OpenApiController(self.config)

    @lazy_property
    def order_api(self):
        return OrderApiController(self.config)

    @lazy_property
    def order_notes_api(self):
        return OrderNotesApiController(self.config)

    @lazy_property
    def product_notes_api(self):
        return ProductNotesApiController(self.config)

    @lazy_property
    def products_api(self):
        return ProductsApiController(self.config)

    @lazy_property
    def security(self):
        return SecurityController(self.config)

    @lazy_property
    def vendor_api(self):
        return VendorApiController(self.config)

    @lazy_property
    def vendor_contact_api(self):
        return VendorContactApiController(self.config)

    @lazy_property
    def vendor_product_options_api(self):
        return VendorProductOptionsApiController(self.config)

    @lazy_property
    def vendor_shipping_api(self):
        return VendorShippingApiController(self.config)

    @lazy_property
    def websites_api(self):
        return WebsitesApiController(self.config)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, timeout=60,
                 max_retries=0, backoff_factor=2,
                 retry_statuses=[408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                 retry_methods=['GET', 'PUT'],
                 environment=Environment.PRODUCTION, access_token='',
                 config=None):
        if config is None:
            self.config = Configuration(
                                         http_client_instance=http_client_instance,
                                         override_http_client_configuration=override_http_client_configuration,
                                         timeout=timeout,
                                         max_retries=max_retries,
                                         backoff_factor=backoff_factor,
                                         retry_statuses=retry_statuses,
                                         retry_methods=retry_methods,
                                         environment=environment,
                                         access_token=access_token)
        else:
            self.config = config
