# -*- coding: utf-8 -*-

"""
bdfs

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DescriptionColumns(object):

    """Implementation of the 'DescriptionColumns' model.

    TODO: type model description here.

    Attributes:
        column_name (string): The description for the column name. Will be
            translated by babel

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "column_name": 'column_name'
    }

    def __init__(self,
                 column_name=None):
        """Constructor for the DescriptionColumns class"""

        # Initialize members of the class
        self.column_name = column_name

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        column_name = dictionary.get('column_name')

        # Return an object of this model
        return cls(column_name)
