# -*- coding: utf-8 -*-

"""
bdfs

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class GetItemSchema(object):

    """Implementation of the 'get_item_schema' model.

    TODO: type model description here.

    Attributes:
        columns (list of string): TODO: type description here.
        keys (list of Key1Enum): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "columns": 'columns',
        "keys": 'keys'
    }

    def __init__(self,
                 columns=None,
                 keys=None):
        """Constructor for the GetItemSchema class"""

        # Initialize members of the class
        self.columns = columns
        self.keys = keys

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        columns = dictionary.get('columns')
        keys = dictionary.get('keys')

        # Return an object of this model
        return cls(columns,
                   keys)
