# -*- coding: utf-8 -*-

"""
bdfs

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Key1Enum(object):

    """Implementation of the 'Key1' enum.

    TODO: type enum description here.

    Attributes:
        SHOW_COLUMNS: TODO: type description here.
        DESCRIPTION_COLUMNS: TODO: type description here.
        LABEL_COLUMNS: TODO: type description here.
        SHOW_TITLE: TODO: type description here.
        NONE: TODO: type description here.

    """

    SHOW_COLUMNS = 'show_columns'

    DESCRIPTION_COLUMNS = 'description_columns'

    LABEL_COLUMNS = 'label_columns'

    SHOW_TITLE = 'show_title'

    NONE = 'none'
