# -*- coding: utf-8 -*-

"""
bdfs

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class KeyEnum(object):

    """Implementation of the 'Key' enum.

    TODO: type enum description here.

    Attributes:
        ADD_COLUMNS: TODO: type description here.
        EDIT_COLUMNS: TODO: type description here.
        FILTERS: TODO: type description here.
        PERMISSIONS: TODO: type description here.
        ADD_TITLE: TODO: type description here.
        EDIT_TITLE: TODO: type description here.
        NONE: TODO: type description here.

    """

    ADD_COLUMNS = 'add_columns'

    EDIT_COLUMNS = 'edit_columns'

    FILTERS = 'filters'

    PERMISSIONS = 'permissions'

    ADD_TITLE = 'add_title'

    EDIT_TITLE = 'edit_title'

    NONE = 'none'
