# -*- coding: utf-8 -*-

"""
bdfs

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderNotesApiGetList(object):

    """Implementation of the 'OrderNotesApi.get_list' model.

    TODO: type model description here.

    Attributes:
        id (int): TODO: type description here.
        note (string): TODO: type description here.
        order_id (int): TODO: type description here.
        mtype (object): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "note": 'note',
        "order_id": 'order_id',
        "id": 'id',
        "mtype": 'type'
    }

    def __init__(self,
                 note=None,
                 order_id=None,
                 id=None,
                 mtype=None):
        """Constructor for the OrderNotesApiGetList class"""

        # Initialize members of the class
        self.id = id
        self.note = note
        self.order_id = order_id
        self.mtype = mtype

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        note = dictionary.get('note')
        order_id = dictionary.get('order_id')
        id = dictionary.get('id')
        mtype = dictionary.get('type')

        # Return an object of this model
        return cls(note,
                   order_id,
                   id,
                   mtype)
