# -*- coding: utf-8 -*-

"""
bdfs

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ProviderEnum(object):

    """Implementation of the 'Provider' enum.

    Choose an authentication provider

    Attributes:
        DB: TODO: type description here.
        LDAP: TODO: type description here.

    """

    DB = 'db'

    LDAP = 'ldap'
